import type {Metadata} from "next";
import {Geist, Geist_Mono, JetBrains_Mono} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import {ThemeProvider} from "@/components/theme-provider";
import Link from "next/link";

const jetbrainsMono = JetBrains_Mono({subsets: ['latin'], variable: '--font-mono'});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-mono", jetbrainsMono.variable)}
        >
        {/*min-h-full flex flex-col*/}
        <body>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange={false}>
            <div>
                <nav className={" border-b px-8 py-4 flex item-center justify-between"}>
                    <h1 className={"text-2xl font-bold text-blue-600"}>My Next</h1>
                    <div className={"flex gap-6"}>
                        <Link href="/dashboard" className={"hover:text-blue-600 transition-colors"}>Home</Link>
                        <Link href={"/about"} className={"hover:text-blue-600 transition-colors"}>About</Link>
                    </div>
                </nav>
                {children}
            </div>
        </ThemeProvider>
        </body>
        </html>
    );
}
